sap.ui.define([
	"colpal/ppm/projectmgmt/model/formatter"
], function(formatter) {
	"use strict";
	return {
		getColumnCatalog: function(oContext) {
			var oColumns = {
				"ColumnCollection": [{
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailItemName"),
					"path": "PPMData>ItemDesc",
					"visible": true,
					"columnIndex": 0
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailItemId"),
					"path": "PPMData>ItemId",
					"visible": true,
					"columnIndex": 1
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailCategoryDesc"),
					"path": "PPMData>CategoryDesc",
					"visible": true,
					"columnIndex": 2
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailSubcategoryDesc"),
					"path": "PPMData>SubcategoryDesc",
					"visible": true,
					"columnIndex": 3
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailDivisionDesc"),
					"path": "PPMData>DivisionDesc",
					"visible": true,
					"columnIndex": 4
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailHubDesc"),
					"path": "PPMData>HubDesc",
					"visible": true,
					"columnIndex": 5
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailLaunchDate"),
					"path": "PPMData>LaunchDate",
					"visible": true,
					"columnIndex": 6
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailInnovationTypeDesc"),
					"path": "PPMData>InnovationDesc",
					"visible": true,
					"columnIndex": 7
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailItemTypeDesc"),
					"path": "PPMData>ItemtypeDesc",
					"visible": true,
					"columnIndex": 8
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailPhaseDesc"),
					"path": "PPMData>PhaseDesc",
					"visible": true,
					"columnIndex": 9
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailStatusDesc"),
					"path": "PPMData>PhasestatusDesc",
					"visible": true,
					"columnIndex": 10
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailStartDate"),
					"path": "PPMData>StartDate",
					"visible": false,
					"columnIndex": 11
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailCurrencyDesc"),
					"path": "PPMData>CurrencyDesc",
					"visible": false,
					"columnIndex": 12
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailGrid"),
					"path": "PPMData>Grid",
					"visible": false,
					"columnIndex": 13
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailBrand"),
					"path": "PPMData>BrandDesc",
					"visible": false,
					"columnIndex": 14
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailSubbrandDesc"),
					"path": "PPMData>SubbrandDesc",
					"visible": false,
					"columnIndex": 15
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailStarfoDesc"),
					"path": "PPMData>StarfoDesc",
					"visible": false,
					"columnIndex": 16
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailProjmanagerDesc"),
					"path": "PPMData>ProjmanagerDesc",
					"visible": false,
					"columnIndex": 17
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailFinamanagerDesc"),
					"path": "PPMData>FinamanagerDesc",
					"visible": false,
					"columnIndex": 18
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailCreatedbyDesc"),
					"path": "PPMData>CreatedbyDesc",
					"visible": false,
					"columnIndex": 19
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailCreatedDate"),
					"path": "PPMData>CreatedDate",
					"visible": false,
					"columnIndex": 20
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailMarkobjeDesc"),
					"path": "PPMData>MarkobjeDesc",
					"visible": false,
					"columnIndex": 21
				}],
				"SortItems": [{
					// "columnKey": "PPMData>ItemId",
					"columnKey": "ItemId",
					"operation": "Descending"
				}],
				"FilterItems": [{
					columnKey: "PPMData>ItemtypeDesc",
					operation: "Contains",
					value1: "Innovation Management",
					value2: "",
					exclude: false
				}],
				"GlobalFilter": {},
				"FixedColumnConfig": [{
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailItemName"),
					"path": "PPMData>ItemDesc",
					"width": "12rem",
					"visible": true,
					"columnIndex": 0
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailItemId"),
					"path": "PPMData>ItemId",
					"width": "6rem",
					"visible": true,
					"columnIndex": 1
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailCategoryDesc"),
					"path": "PPMData>CategoryDesc",
					"width": "8rem",
					"visible": true,
					"columnIndex": 2
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailSubcategoryDesc"),
					"path": "PPMData>SubcategoryDesc",
					"width": "8rem",
					"visible": true,
					"columnIndex": 3
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailDivisionDesc"),
					"path": "PPMData>DivisionDesc",
					"width": "8rem",
					"visible": true,
					"columnIndex": 4
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailHubDesc"),
					"path": "PPMData>HubDesc",
					"width": "8rem",
					"visible": true,
					"columnIndex": 5
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailLaunchDate"),
					"path": "PPMData>LaunchDate",
					"width": "8rem",
					"visible": true,
					"columnIndex": 6
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailInnovationTypeDesc"),
					"path": "PPMData>InnovationDesc",
					"width": "8rem",
					"visible": true,
					"columnIndex": 7
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailItemTypeDesc"),
					"path": "PPMData>ItemtypeDesc",
					"width": "12rem",
					"visible": false,
					"columnIndex": 8
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailPhaseDesc"),
					"path": "PPMData>PhaseDesc",
					"width": "11rem",
					"visible": true,
					"columnIndex": 9
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailStatusDesc"),
					"path": "PPMData>PhasestatusDesc",
					"width": "6rem",
					"visible": true,
					"columnIndex": 10
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailStartDate"),
					"path": "PPMData>StartDate",
					"width": "6rem",
					"visible": false,
					"columnIndex": 11
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailCurrencyDesc"),
					"path": "PPMData>CurrencyDesc",
					"width": "6rem",
					"visible": false,
					"columnIndex": 12
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailGrid"),
					"path": "PPMData>Grid",
					"width": "6rem",
					"visible": false,
					"columnIndex": 13
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailBrand"),
					"path": "PPMData>BrandDesc",
					"width": "6rem",
					"visible": false,
					"columnIndex": 14
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailSubbrandDesc"),
					"path": "PPMData>SubbrandDesc",
					"width": "6rem",
					"visible": false,
					"columnIndex": 15
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailStarfoDesc"),
					"path": "PPMData>StarfoDesc",
					"width": "8rem",
					"visible": false,
					"columnIndex": 16
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailProjmanagerDesc"),
					"path": "PPMData>ProjmanagerDesc",
					"width": "8rem",
					"visible": false,
					"columnIndex": 17
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailFinamanagerDesc"),
					"path": "PPMData>FinamanagerDesc",
					"width": "8rem",
					"visible": false,
					"columnIndex": 18
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailCreatedbyDesc"),
					"path": "PPMData>CreatedbyDesc",
					"width": "8rem",
					"visible": false,
					"columnIndex": 19
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailCreatedDate"),
					"path": "PPMData>CreatedDate",
					"width": "6rem",
					"visible": false,
					"columnIndex": 20
				}, {
					"text": oContext.getOwnerComponent().getModel("i18n").getProperty("detailMarkobjeDesc"),
					"path": "PPMData>MarkobjeDesc",
					"width": "8rem",
					"visible": false,
					"columnIndex": 21
				}],
				OtherConfig: {
					MaxTableRows: 10
				}
			};
			return oColumns;
		}
	};
});